# Generated by Django 2.2.4 on 2019-08-16 03:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(choices=[('', '--- Select Product Type ---'), ('McBookPro', 'MacBook Pro'), ('macbook_air', 'MacBook Air'), ('iPad', 'iPad'), ('iPhone', 'iPhone')], max_length=100)),
                ('condition', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('year', models.CharField(choices=[('', '-- Select Year --'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019')], default='', max_length=100)),
                ('inch', models.IntegerField(default='0')),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('product_image', models.ImageField(default='products_image/default.png', upload_to='products_image')),
                ('description', models.TextField(default='Say Something here', max_length=1000)),
            ],
        ),
    ]
