# Generated by Django 2.2.4 on 2019-09-24 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190816_0328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_name',
            new_name='product_category',
        ),
    ]
