# Generated by Django 2.2.4 on 2019-09-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190924_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='product_state',
            field=models.CharField(choices=[('', 'Select State'), ('New', 'New '), ('Used', 'Used '), ('Damaged', 'Damaged ')], default='Used', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_category',
            field=models.CharField(choices=[('', '--- Select Product Type ---'), ('MacBook Pro', 'MacBook Pro'), ('MacBook Air', 'MacBook Air'), ('iPad', 'iPad'), ('iPhone', 'iPhone')], max_length=100),
        ),
    ]
