# Generated by Django 2.2.4 on 2019-09-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('testimonial', models.TextField()),
                ('user_image', models.ImageField(default='testimonials-img/default.png', upload_to='testimonials-img')),
                ('user_type', models.CharField(choices=[('', 'Select User Type'), ('CLients', 'Client'), ('Supplyer', 'Supplyer'), ('Employee', 'Employee'), ('Developer', 'Developer')], max_length=100)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
