# Generated by Django 2.2.4 on 2019-09-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='display',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='user_type',
            field=models.CharField(choices=[('', 'Select User Type'), ('Client', 'Client'), ('Supplyer', 'Supplyer'), ('Employee', 'Employee'), ('Developer', 'Developer')], max_length=100),
        ),
    ]
