# Generated by Django 2.2.4 on 2019-10-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20190929_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_category',
            field=models.CharField(choices=[('', 'Select Product Type'), ('MacBook Pro', 'MacBook Pro'), ('MacBook Air', 'MacBook Air'), ('iPad', 'iPad'), ('iPhone', 'iPhone')], max_length=100),
        ),
    ]
