# Generated by Django 2.2.4 on 2019-10-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_order_ordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='orderd',
            new_name='ordered',
        ),
        migrations.AlterField(
            model_name='products',
            name='product_category',
            field=models.CharField(choices=[('', 'Select Product Type'), ('MacBook Pro', 'MacBook Pro'), ('MacBook Air', 'MacBook Air'), ('iPad', 'iPad'), ('iMac', 'iMac'), ('iPhone', 'iPhone')], max_length=100),
        ),
    ]
