# Generated by Django 2.2.4 on 2019-10-31 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20191031_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='product',
            new_name='products',
        ),
    ]
