# Generated by Django 2.2.4 on 2019-11-02 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20191102_0204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='products',
            new_name='product',
        ),
    ]
