# Generated by Django 2.2.4 on 2019-11-02 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20191102_0214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='product',
            new_name='products',
        ),
    ]
