# Generated by Django 2.2.4 on 2019-11-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20191102_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='products.OrderProduct'),
        ),
    ]
