# Generated by Django 2.2.4 on 2019-11-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_products_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(default='Say Something here', max_length=10000),
        ),
    ]
