# Generated by Django 2.2.4 on 2019-11-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_order_billing_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, unique=True),
        ),
    ]
